# Configuration for the ZMQ Client (PULL)
/**/network_bridge_client:
  ros__parameters:
    network_interface: "network_bridge::ZmqInterface"

    ZmqInterface:
      role: "client"
      remote_address: "127.0.0.1"
      port: 5555

    default_rate: 10.0
    default_zstd_level: 3
    publish_stale_data: False

    # We use a publish namespace so that it doesn't clash with the server's subscription on the same machine
    subscribe_namespace: ""
    publish_namespace: "/client_side"
